version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: Rg.Plugins.Popup
    versions:
    - 2.0.0.10
